package singbox

// DefaultProtocols returns the standard list of 22 supported protocols when sing-box CLI is not yet installed.
func DefaultProtocols() []ProtocolInfo {
	return []ProtocolInfo{
		{
			ID:          "reality",
			Name:        "VLESS-REALITY",
			Category:    "recommended",
			Recommended: true,
			Transport:   "tcp",
			TLS:         "reality",
			Description: "顶级抗审查伪装，直接借用海外权威名站 TLS 指纹，无需自行配置域名",
			Args:        []string{"port", "uuid", "sni"},
		},
		{
			ID:          "rh2",
			Name:        "VLESS-HTTP2-REALITY",
			Category:    "recommended",
			Recommended: true,
			Transport:   "http2",
			TLS:         "reality",
			Description: "HTTP/2 多路复用 + REALITY TLS 双重伪装，高并发大吞吐免配域名",
			Args:        []string{"port", "uuid", "sni"},
		},
		{
			ID:          "hy2",
			Name:        "Hysteria2",
			Category:    "recommended",
			Recommended: true,
			Transport:   "udp",
			TLS:         "self-signed",
			Description: "基于定制 QUIC 协议，针对跨洋恶劣网络与高丢包极速狂飙",
			Args:        []string{"port", "password"},
		},
		{
			ID:          "tuic",
			Name:        "TUIC v5",
			Category:    "recommended",
			Recommended: true,
			Transport:   "quic",
			TLS:         "self-signed",
			Description: "基于 QUIC 拥塞控制 BBR 协议，低延迟抗抖动高可靠",
			Args:        []string{"port", "uuid"},
		},
		{
			ID:          "ss",
			Name:        "Shadowsocks 2022",
			Category:    "recommended",
			Recommended: true,
			Transport:   "tcp/udp",
			TLS:         "none",
			Description: "现代 Shadowsocks 2022 规范，性能极高客户端广泛支持",
			Args:        []string{"port", "password", "method"},
		},
		{
			ID:          "trojan",
			Name:        "Trojan",
			Category:    "popular",
			Recommended: false,
			Transport:   "tcp",
			TLS:         "tls",
			Description: "经典伪装 HTTPS 协议，流量表现为正常安全网页浏览",
			Args:        []string{"port", "password"},
		},
		{
			ID:          "anytls",
			Name:        "AnyTLS",
			Category:    "popular",
			Recommended: false,
			Transport:   "tcp",
			TLS:         "acme/tls",
			Description: "多路径 TLS 传输协议，具备抗阻断特性",
			Args:        []string{"port", "password", "domain"},
		},
		{
			ID:          "socks",
			Name:        "Socks5",
			Category:    "popular",
			Recommended: false,
			Transport:   "tcp",
			TLS:         "none",
			Description: "标准 Socks5 代理入站，局域网与前置分流首选",
			Args:        []string{"port", "username", "password"},
		},
		{
			ID:          "direct",
			Name:        "Direct (端口转发)",
			Category:    "popular",
			Recommended: false,
			Transport:   "tcp",
			TLS:         "none",
			Description: "透明 TCP 端口流量中继直通",
			Args:        []string{"port", "remote_addr", "remote_port"},
		},
		{
			ID:          "vws",
			Name:        "VLESS-WS-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "ws",
			TLS:         "tls",
			Description: "VLESS + WebSocket + TLS，支持 Cloudflare CDN 优选反代免封",
			Args:        []string{"host", "uuid", "path"},
		},
		{
			ID:          "wss",
			Name:        "VMess-WS-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "ws",
			TLS:         "tls",
			Description: "VMess + WebSocket + TLS，经典 CDN 拯救被墙 IP 方案",
			Args:        []string{"host", "uuid", "path"},
		},
		{
			ID:          "tws",
			Name:        "Trojan-WS-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "ws",
			TLS:         "tls",
			Description: "Trojan + WebSocket + TLS，结合 CDN 隐藏源站真实地址",
			Args:        []string{"host", "password", "path"},
		},
		{
			ID:          "vhu",
			Name:        "VLESS-HTTPUpgrade-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "httpupgrade",
			TLS:         "tls",
			Description: "新一代 HTTPUpgrade 传输，比 WS 更省服务端 CPU 资源",
			Args:        []string{"host", "uuid", "path"},
		},
		{
			ID:          "hu",
			Name:        "VMess-HTTPUpgrade-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "httpupgrade",
			TLS:         "tls",
			Description: "VMess + HTTPUpgrade 现代化高性能传输",
			Args:        []string{"host", "uuid", "path"},
		},
		{
			ID:          "thu",
			Name:        "Trojan-HTTPUpgrade-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "httpupgrade",
			TLS:         "tls",
			Description: "Trojan + HTTPUpgrade 传输",
			Args:        []string{"host", "password", "path"},
		},
		{
			ID:          "vh2",
			Name:        "VLESS-H2-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "http2",
			TLS:         "tls",
			Description: "VLESS + HTTP/2 多路复用 + TLS",
			Args:        []string{"host", "uuid", "path"},
		},
		{
			ID:          "h2",
			Name:        "VMess-H2-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "http2",
			TLS:         "tls",
			Description: "VMess + HTTP/2 多路复用 + TLS",
			Args:        []string{"host", "uuid", "path"},
		},
		{
			ID:          "th2",
			Name:        "Trojan-H2-TLS",
			Category:    "cdn",
			Recommended: false,
			Transport:   "http2",
			TLS:         "tls",
			Description: "Trojan + HTTP/2 多路复用 + TLS",
			Args:        []string{"host", "password", "path"},
		},
		{
			ID:          "ws",
			Name:        "VMess-WS",
			Category:    "raw",
			Recommended: false,
			Transport:   "ws",
			TLS:         "none",
			Description: "纯 WebSocket 传输，便于前置 Nginx/Caddy 自建反向代理",
			Args:        []string{"port", "uuid"},
		},
		{
			ID:          "tcp",
			Name:        "VMess-TCP",
			Category:    "raw",
			Recommended: false,
			Transport:   "tcp",
			TLS:         "none",
			Description: "原生 TCP 传输，开销极低",
			Args:        []string{"port", "uuid"},
		},
		{
			ID:          "http",
			Name:        "VMess-HTTP",
			Category:    "raw",
			Recommended: false,
			Transport:   "http",
			TLS:         "none",
			Description: "伪装 HTTP/1.1 明文传输",
			Args:        []string{"port", "uuid"},
		},
		{
			ID:          "quic",
			Name:        "VMess-QUIC",
			Category:    "raw",
			Recommended: false,
			Transport:   "quic",
			TLS:         "none",
			Description: "基于原生 QUIC 协议传输",
			Args:        []string{"port", "uuid"},
		},
	}
}
