package com.nxgate.app.util

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // Common / Navigation
    val appTitle: String,
    val navDashboard: String,
    val navMonitoring: String,
    val navRouting: String,
    val navNodes: String,
    val navSystem: String,
    val refresh: String,
    val close: String,
    val cancel: String,
    val confirm: String,
    val save: String,
    val copy: String,
    val share: String,
    val online: String,
    val offline: String,
    val connected: String,
    val disconnected: String,
    val connecting: String,
    val unknown: String,

    // Cluster Hub
    val clusterMonitor: String,
    val clusterSummary: String,
    val managedHosts: String,
    val hostsOnline: String,
    val hostsOffline: String,
    val liveThroughput: String,
    val downSpeed: String,
    val upSpeed: String,
    val todayTraffic: String,
    val physicalExit: String,
    val aiUnlock: String,
    val activeConns: String,
    val totalTraffic: String,
    val quickRotate: String,
    val getSub: String,
    val console: String,
    val addServer: String,
    val noServers: String,

    // Console
    val consoleOverview: String,
    val primaryGateway: String,
    val concurrentExits: String,
    val liveTrafficStats: String,
    val systemLogs: String,
    val cleartextAlertTitle: String,
    val cleartextAlertMsg: String,
    val sseReconnecting: String,

    // Matrix
    val portMatrixTitle: String,
    val portRules: String,
    val dynamicGroups: String,
    val edgeInbounds: String,
    val evaluateRotate: String,
    val addRule: String,
    val addGroup: String,

    // Nodes
    val nodeSquareTitle: String,
    val filterAll: String,
    val filterFavorites: String,
    val filterJapan: String,
    val filterUS: String,
    val filterResidential: String,
    val filterTripleAI: String,
    val setMaster: String,
    val currentMaster: String,
    val startTunnel: String,
    val favorite: String,
    val favorited: String,
    val blacklist: String,
    val sortDefault: String,
    val sortLatencyAsc: String,
    val sortSpeedDesc: String,
    val sortScoreDesc: String,
    val latencyFast: String,
    val latencyGood: String,
    val latencyFair: String,
    val latencyHigh: String,
    val latencyPending: String,

    // System
    val systemTitle: String,
    val versionAndUpdates: String,
    val currentLatest: String,
    val hasUpdateAvailable: String,
    val checkUpdate: String,
    val updateServer: String,
    val releaseNotes: String,
    val ageE2EEncryption: String,
    val ageDesc: String,
    val enableAgeProtection: String,
    val ageRecipientPublicKey: String,
    val generateNewKeyPair: String,
    val deriveFromSecretKey: String,
    val saveAgePolicy: String,
    val subTokenTitle: String,
    val subTokenDesc: String,
    val resetToken: String,
    val saveToken: String,
    val telegramAlertsTitle: String,
    val telegramDesc: String,
    val testAlert: String,
    val saveTelegramConfig: String,
    val maintenanceToolkit: String,
    val refreshMirror: String,
    val shadowProbe: String,
    val clearBlacklist: String,
    val liveLogs: String,

    // Settings
    val settingsTitle: String,
    val serverList: String,
    val securityAndPreferences: String,
    val biometricLock: String,
    val biometricLockDesc: String,
    val backgroundTimeout: String,
    val cleartextWarning: String,
    val cleartextWarningDesc: String,
    val appLanguageTitle: String,
    val appLanguageDesc: String,
    val langSystem: String,
    val langZh: String,
    val langEn: String,
    val themeAndAppearance: String,
    val clusterBackup: String,
    val exportCluster: String,
    val importCluster: String,

    // Subscriptions dialog
    val subDialogTitle: String,
    val subDialogSubtitle: String,
    val ageEncryptedBadge: String,
    val genericSubTitle: String,
    val genericSubDesc: String,
    val clashSubTitle: String,
    val clashSubDesc: String,
    val importToClient: String,
    val importToClash: String
)

val AppStringsZh = AppStrings(
    appTitle = "NXGate",
    navDashboard = "概览",
    navMonitoring = "监控",
    navRouting = "调度",
    navNodes = "节点",
    navSystem = "系统",
    refresh = "刷新",
    close = "关闭",
    cancel = "取消",
    confirm = "确认",
    save = "保存",
    copy = "复制",
    share = "分享",
    online = "在线",
    offline = "离线",
    connected = "已连接",
    disconnected = "未连接",
    connecting = "连接中",
    unknown = "未知",

    clusterMonitor = "VPN 集群监控",
    clusterSummary = "集群全局汇总",
    managedHosts = "纳管主机",
    hostsOnline = "台在线",
    hostsOffline = "台离线",
    liveThroughput = "实时吞吐",
    downSpeed = "下行",
    upSpeed = "上行",
    todayTraffic = "今日总流量",
    physicalExit = "物理出口",
    aiUnlock = "智能解锁",
    activeConns = "活跃连接",
    totalTraffic = "总计",
    quickRotate = "一键换线",
    getSub = "获取订阅",
    console = "控制台",
    addServer = "添加新服务器",
    noServers = "当前暂未纳管任何服务器，请点击右下角按钮或右上角扫码添加 VPS。",

    consoleOverview = "运行概览",
    primaryGateway = "主网卡零号 (tun0)",
    concurrentExits = "并发独立出口",
    liveTrafficStats = "实时流量统计",
    systemLogs = "系统运行日志",
    cleartextAlertTitle = "HTTP 未加密传输提醒",
    cleartextAlertMsg = "当前网关通信未启用 TLS 加密，管理凭据以明文传输，请注意公共网络安全。",
    sseReconnecting = "正在尝试恢复与网关的实时事件推送...",

    portMatrixTitle = "多端口代理与分流",
    portRules = "端口分流规则",
    dynamicGroups = "自适应隧道组",
    edgeInbounds = "边缘入站节点",
    evaluateRotate = "立即评估换线",
    addRule = "添加规则",
    addGroup = "添加动态组",

    nodeSquareTitle = "节点广场",
    filterAll = "全部",
    filterFavorites = "我的收藏",
    filterJapan = "日本",
    filterUS = "美国",
    filterResidential = "原生家宽",
    filterTripleAI = "三大AI全通",
    setMaster = "设为主出口",
    currentMaster = "当前主连",
    startTunnel = "拉起网卡",
    favorite = "收藏",
    favorited = "已收藏",
    blacklist = "屏蔽",
    sortDefault = "默认推荐 (综合排序)",
    sortLatencyAsc = "延迟优先 (从低到高)",
    sortSpeedDesc = "带宽优先 (从大到小)",
    sortScoreDesc = "稳定度优先 (评分最高)",
    latencyFast = "极速",
    latencyGood = "良好",
    latencyFair = "一般",
    latencyHigh = "偏高",
    latencyPending = "待测",

    systemTitle = "系统运维与网关管理",
    versionAndUpdates = "版本与自愈更新",
    currentLatest = "当前已是最新构建",
    hasUpdateAvailable = "发现新版本可用",
    checkUpdate = "检查更新",
    updateServer = "升级服务器",
    releaseNotes = "更新日志",
    ageE2EEncryption = "age 端到端前向安全加密",
    ageDesc = "开启后，服务端下发的通用订阅与分流配置将自动转换为标准 ASCII Armored age 密文。仅持有私钥的受信任端方可解密，杜绝中转节点嗅探与缓存劫持。",
    enableAgeProtection = "开启订阅加密保护",
    ageRecipientPublicKey = "age Recipient 公钥 (age1... / age1pq...)",
    generateNewKeyPair = "生成新密钥对",
    deriveFromSecretKey = "从私钥推导",
    saveAgePolicy = "保存 age 加密策略",
    subTokenTitle = "免密订阅令牌 (SubToken)",
    subTokenDesc = "专属 16 位安全令牌可隔离管理面板路径与密码，供 Clash、sing-box 等外部客户端免认证静默拉取订阅，探测扫描直接返回 404。",
    resetToken = "重置令牌",
    saveToken = "保存令牌",
    telegramAlertsTitle = "Telegram 异常通报与告警",
    telegramDesc = "当 VPS 网关出现物理断流、假死触发 Failover 故障转移换线、或节点池全量拉取异常时，远端通过 Telegram 机器人实时推流通报。",
    testAlert = "测试推送",
    saveTelegramConfig = "保存通知配置",
    maintenanceToolkit = "网关运维与自愈工具箱",
    refreshMirror = "刷新节点源",
    shadowProbe = "影子协议探活",
    clearBlacklist = "清空硬屏蔽",
    liveLogs = "实时日志",

    settingsTitle = "配置与安全设置",
    serverList = "纳管网关列表",
    securityAndPreferences = "安全与偏好",
    biometricLock = "生物识别安全锁",
    biometricLockDesc = "启用指纹、面容或系统凭证保护",
    backgroundTimeout = "后台锁定等待时间",
    cleartextWarning = "明文传输警告",
    cleartextWarningDesc = "连接未加密 HTTP 时提示风险",
    appLanguageTitle = "界面语言 / Language",
    appLanguageDesc = "设置应用的显示语言",
    langSystem = "跟随系统 (Auto)",
    langZh = "简体中文",
    langEn = "English",
    themeAndAppearance = "主题与外观",
    clusterBackup = "集群配置备份与恢复",
    exportCluster = "导出集群",
    importCluster = "导入配置",

    subDialogTitle = "获取节点订阅",
    subDialogSubtitle = "实时聚合多协议出口订阅",
    ageEncryptedBadge = "已开启 age 端到端安全加密保护",
    genericSubTitle = "通用全量订阅 (Base64/Raw)",
    genericSubDesc = "Shadowrocket / v2rayN / sing-box / Surge / Quantumult X",
    clashSubTitle = "Clash Meta / Mihomo (YAML)",
    clashSubDesc = "Clash Verge / Mihomo Party / Stash 专属分流配置",
    importToClient = "导入客户端",
    importToClash = "导入 Clash"
)

val AppStringsEn = AppStrings(
    appTitle = "NXGate",
    navDashboard = "Dashboard",
    navMonitoring = "Monitor",
    navRouting = "Routing",
    navNodes = "Nodes",
    navSystem = "System",
    refresh = "Refresh",
    close = "Close",
    cancel = "Cancel",
    confirm = "Confirm",
    save = "Save",
    copy = "Copy",
    share = "Share",
    online = "Online",
    offline = "Offline",
    connected = "Connected",
    disconnected = "Disconnected",
    connecting = "Connecting",
    unknown = "Unknown",

    clusterMonitor = "VPN Cluster Monitor",
    clusterSummary = "Cluster Summary",
    managedHosts = "Managed Hosts",
    hostsOnline = " online",
    hostsOffline = " offline",
    liveThroughput = "Throughput",
    downSpeed = "Down",
    upSpeed = "Up",
    todayTraffic = "Today's Traffic",
    physicalExit = "Exit IP",
    aiUnlock = "AI Unlock",
    activeConns = "Connections",
    totalTraffic = "Total",
    quickRotate = "Rotate",
    getSub = "Subscription",
    console = "Console",
    addServer = "Add Server",
    noServers = "No servers added yet. Tap the button or scan QR to add a VPS gateway.",

    consoleOverview = "Overview",
    primaryGateway = "Primary Gateway (tun0)",
    concurrentExits = "Concurrent Exits",
    liveTrafficStats = "Live Traffic Stats",
    systemLogs = "System Logs",
    cleartextAlertTitle = "Unencrypted HTTP Warning",
    cleartextAlertMsg = "Current gateway communication is not encrypted with TLS. Credentials are sent in cleartext.",
    sseReconnecting = "Restoring real-time SSE stream...",

    portMatrixTitle = "Port Proxy & Routing",
    portRules = "Port Rules",
    dynamicGroups = "Dynamic Groups",
    edgeInbounds = "Edge Inbounds",
    evaluateRotate = "Evaluate & Rotate",
    addRule = "Add Rule",
    addGroup = "Add Group",

    nodeSquareTitle = "Node Square",
    filterAll = "All",
    filterFavorites = "Favorites",
    filterJapan = "Japan",
    filterUS = "US",
    filterResidential = "Residential",
    filterTripleAI = "Triple AI",
    setMaster = "Set Master",
    currentMaster = "Current Master",
    startTunnel = "Start Dev",
    favorite = "Favorite",
    favorited = "Favorited",
    blacklist = "Block",
    sortDefault = "Default (Score)",
    sortLatencyAsc = "Lowest Latency",
    sortSpeedDesc = "Highest Speed",
    sortScoreDesc = "Top Reliability",
    latencyFast = "Fast",
    latencyGood = "Good",
    latencyFair = "Fair",
    latencyHigh = "High",
    latencyPending = "Wait",

    systemTitle = "System & Maintenance",
    versionAndUpdates = "Version & Updates",
    currentLatest = "Up to date",
    hasUpdateAvailable = "New update available",
    checkUpdate = "Check Updates",
    updateServer = "Update Server",
    releaseNotes = "Release Notes",
    ageE2EEncryption = "age E2E Encryption",
    ageDesc = "When enabled, subscriptions are emitted as standard ASCII Armored age ciphertext. Only trusted clients holding the secret key can decrypt.",
    enableAgeProtection = "Enable age Subscription Encryption",
    ageRecipientPublicKey = "age Recipient Public Key (age1... / age1pq...)",
    generateNewKeyPair = "Generate Keys",
    deriveFromSecretKey = "Derive from Secret",
    saveAgePolicy = "Save age Policy",
    subTokenTitle = "Subscription Token (SubToken)",
    subTokenDesc = "Dedicated 16-character token isolates admin path and credentials for seamless client subscription delivery.",
    resetToken = "Reset Token",
    saveToken = "Save Token",
    telegramAlertsTitle = "Telegram Notifications",
    telegramDesc = "Receive instant alerts on channel/chat when stream breaks, failover occurs, or pool refreshes.",
    testAlert = "Test Alert",
    saveTelegramConfig = "Save Alerts",
    maintenanceToolkit = "Maintenance Toolkit",
    refreshMirror = "Refresh Mirror",
    shadowProbe = "Shadow Probe",
    clearBlacklist = "Clear Blacklist",
    liveLogs = "Live Logs",

    settingsTitle = "Settings & Security",
    serverList = "Gateway Servers",
    securityAndPreferences = "Security & Preferences",
    biometricLock = "Biometric Lock",
    biometricLockDesc = "Protect access with fingerprint, face, or PIN",
    backgroundTimeout = "Background Lock Timeout",
    cleartextWarning = "Cleartext Warning",
    cleartextWarningDesc = "Warn when connecting to unencrypted HTTP",
    appLanguageTitle = "Language",
    appLanguageDesc = "Set app display language",
    langSystem = "Follow System (Auto)",
    langZh = "简体中文 (Chinese)",
    langEn = "English",
    themeAndAppearance = "Theme & Appearance",
    clusterBackup = "Cluster Backup & Restore",
    exportCluster = "Export Cluster",
    importCluster = "Import Config",

    subDialogTitle = "Get Subscriptions",
    subDialogSubtitle = "Aggregated multi-protocol egress subscriptions",
    ageEncryptedBadge = "Protected by age end-to-end encryption",
    genericSubTitle = "Universal Subscription (Base64/Raw)",
    genericSubDesc = "Shadowrocket / v2rayN / sing-box / Surge / Quantumult X",
    clashSubTitle = "Clash Meta / Mihomo (YAML)",
    clashSubDesc = "Clash Verge / Mihomo Party / Stash routing config",
    importToClient = "Import Client",
    importToClash = "Import Clash"
)

val LocalAppStrings = staticCompositionLocalOf<AppStrings> { AppStringsZh }
